spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ifba.coordinator@gmail.com
    password: 123456789Rr
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
    test-connection: false

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    hibernate:
      jdbc: time_zone = TimeZone
